spring:
  profiles:
    active: dev
  application:
    name: igse-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
      routes:
        - id:
          uri: lb://IGSE-CORE
          predicates:
            - Path=/igse/core/**
          filters:
            - GateWayFilter
        - id: igse-auth
          uri: lb://IGSE-AUTH
          predicates:
            - Path=/igse/auth/**


server:
  port: 8080
eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

