spring:
  application:
    name: igse-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
      routes:
        - id:
          uri: ${igse.gateway.base-url.igse-core}
          predicates:
            - Path=/igse/core/**
          filters:
            - GateWayFilter
        - id: igse-auth
          uri: ${igse.gateway.base-url.igse-auth}
          predicates:
            - Path=/igse/auth/**
        - id: igse-payment
          uri: ${igse.gateway.base-url.igse-payment}
          predicates:
            - Path=/igse-payment/**
          filters:
            - GateWayFilter


server:
  port: 8080
eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
logging:
  pattern:
    console: "%clr(IST=){faint}%clr(%d{yyyy-MM-dd'|'HH:mm:ss, Asia/Kolkata}){faint} [%t] %clr(APP=){faint}%clr(${spring.application.name:null}){yellow} %clr(LEVEL=){faint}%clr(${LOG_LEVEL_PATTERN:%p}) %clr(CLASS=){faint}%clr(%logger{26}){cyan} %clr(X-Correlation-Id=){faint}%clr(%X{correlation-Id:-}){reverse} | %m%n%ex"