spring:
  application:
    name: igse-gateway
  cloud:
    gateway:
      routes:
        - id: igse-auth
          uri: lb://IGSE-AUTH
          predicates:
            - Path=/igse/auth/**

server:
  port: 8080
eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

